
= How to install CadQuery and CQ-editor

== Install miniconda
The installation packages for miniconda for Windows, Linux and MacOS can be found at the following web-location: 

[source]
----
https://docs.conda.io/en/latest/miniconda.html
----

The installation on MacOS and Windows is completely automated. In both operating environments it is probably best to install it only for the current user. 

== Install CadQuery and CQ-editor on Windows
After installing miniconda, open a shell with miniconda environment. On Windows the conda shell can be opened from the start-menu. If you installed the latest installation package for Miniconda3 there will be an item called Anaconda3 in the start-menu that contains the item "Anaconda prompt". Use the following command to install cadquery: 

[source, bash]
----
conda install -c cadquery -c conda-forge cadquery=master
----

To be sure the installation was succesful, you can run the following set of commands: 

[source, python]
----
python
import cadquery
cadquery.Workplane('XY').box(1,2,3).toSvg()
----


open conda prompt

----
conda -V   check version
conda create --name cqtest python=3.8
----

creates a virtual environment "cqtest" and installs python and pip into it, 

----
conda activate cqtest
----

You can leave the prompt with 

[source, python]
---- 
exit()
----

Next install the cq-editor. 

[source, python]
---- 
conda install -c cadquery -c conda-forge cq-editor=master
----


start the cq-editor with the command "cq-editor"


== Install CadQuery and CQ-editor on MacOS
The installation on MacOS is almost completely identical to the installation on Windows. cq-editor


pip install cadquery2
```
conda install -c cadquery -c conda-forge cadquery=master
```
pip install cadquery-server

```
conda install -c cadquery -c conda-forge cq-editor=master
```


On MacOS


install miniconda (latest release)

open terminal, check with 
conda -V

conda create --name cqtest python


to start working with cadquery from VS Code: 

open terminal
conda activate cqtest
cq-server
